### ISSUE TITLE
Automatyczne anulowanie transakcji nie przywraca kodów rabatowych

### ISSUE THREAD

**Issue by flexcodenet** [PayU-EMEA/plugin_magento_24#10]
W momencie niepowodzenia płatności w systemie, moduł sam nadaje status "anulowane" w magento.
Co jest błędnym krokiem, bo co w momencie gdy ktoś chce skorzystać z opcji zapłać ponownie?

Dodatkowo, proces anulowania odbywa się w sposób błędny, bo np. nie powracają kody rabatowe do puli działania.
W przypadku anulacji manualnej w panelu przez obsługę sklepu, ten problem nie występuje.
Gdy ten status nadaje moduł PayU, wówczas nie można ponownie użyć kodu rabatowego.

Problem występuje w najnowszej wersji 1.0.3.

**Comment by regdos** [comment]
@flexcodenet 
W przypadku włączonego ponowienia płatności zamówienie nie powinno się anulować. Sprawdzę czy mogę to powtórzyć. Czy może Pan podać numer POS lub adres sklepu to sprawdzę konfigurację i jak to wygląda ze strony PayU.  

Kwestię kodu rabatowego też prześledzę.

**Comment by flexcodenet** [comment]
@regdos Status 'anulowany' automatycznie jest nadawany w momencie gdy opcja 'ponawiania płatności' jest wyłączona, czy taki przypadek Pan weryfikował? W momencie gdy jest ona aktywna, to fakt, nie jest nadawany status 'anulowane'.

Okej, czekam na wyniki.

**Comment by regdos** [comment]
@flexcodenet 
W kwestii przywracania kodu rabatowego proszę przetestować poprawkę https://github.com/PayU-EMEA/plugin_magento_24/commit/5927619c8c07d422c5849c0bb2d9013727b92513 proszę pamiętać o `setup:di:compile` bo zmieniła się sygnatura metody. 

W przypadku gdy nie uda się płatność w PayU i wyślemy notyfikację z PayU do sklepu to możliwe są dwie akcje: 
* gdy włączone jest ponowienie płatności na metodzie PayU, którą była wykonywana płatność - zamówienie pozostaje w statusie bez zmian żeby można było wykonać kolejną płatność przez PayU
* gdy ponowienie jest wyłączone - zamówienie jest anulowane

Takie działanie przyjęliśmy w naszych wtyczkach. W M2 nie ma statusu np. payment_failed albo jakiegoś, którym można oznaczyć zamówienia, do których nie udała się płatność. 

Jeżeli faktycznie ma Pan taki przypadek, że jeżeli po nieudanej płatności chce Pan dalej procesować to zamówienie np. zwykłym przelewem bankowym to możemy dorobić opcję w panelu, że po zaznaczeniu jej zamówienie nie jest anulowane.

**Comment by flexcodenet** [comment]
@regdos sprawdzę poprawkę i dam znać.

Tak posiadam takie przypadki, że właśnie zwykłym przelewem jest procesowane, stąd jeśli jest taka możliwość utworzenia tej opcji, to jestem za.

**Comment by flexcodenet** [comment]
@regdos Aktualnie po wprowadzeniu zmiany i wyłączonym ponawianiu płatności, wybierając negatywną autoryzację, zamówienie nie otrzymuje statusu "Anulowane".

**Comment by regdos** [comment]
@flexcodenet 
Jest problem z dostarczeniem notyfikacji, Pana strona odpowiada 500 a proces zmiany statusów opiera się o te notyfikajce np. 
```
<h1>There has been an error processing your request</h1>
<p><em>Exception printing is disabled by default for security reasons.</em></p>
<p>Error log record number: 1cb7940d664e4b8f609cdfd929d447b51ca844732a7a13d7a565f6e4a2700ae4</p>
``` 

Proszę sprawdzić w log-ach co się pojawia dla powyższego identyfikatora.

**Comment by flexcodenet** [comment]
@regdos I to jest z wczoraj tak?

**Comment by flexcodenet** [comment]
@regdos Fakt, błąd występował, poprawiono i wpadło anulowane, przed chwilą test zrobiłem. Rozumiem, że funkcja wyłączająca anulowanie będzie utworzona?

**Comment by regdos** [comment]
@flexcodenet tak ale nie umiem określić dokładnie kiedy. A czy kod rabatowy został przywrócony?

**Comment by flexcodenet** [comment]
@regdos Działa poprawnie, kupon można wykorzystać ponownie.

**Comment by flexcodenet** [comment]
@regdos Znana jest data publikacji nowej wersji?

**Comment by regdos** [comment]
@flexcodenet Nowa wersja została wydana, przepraszamy za opóźnienie. 
Zamykam to zgłoszenie, dla wyłączanie anulowania proszę założyć nowe.
