### ISSUE TITLE
Bug repayment on magento 2.4.2

### ISSUE THREAD

**Issue by CptShooter** [PayU-EMEA/plugin_magento_24#14]
Hello,

I have detected a problem with the re-payment functionality in this version of the module.
The bug was detected on magento 2.4.2 with many other modules. To be sure, I also checked on the pure magento 2.4.3 website only with your module and the mageplaza SMTP module. 

Everything is fine on the magento 2.3.5p2 with your plugin_magento_23 module. 

There is an exception when clicking on the link to re-payment in the e-mail message.
I noticed that the link does not contain order_id even though the generating method in the template should put it there 
`https://example.com/sales/order/repayview/hash/06a92f5bbb8cb7836d526b43496b1f33/`

When I click on the link I get the following error: 
<pre>1 exception(s):
Exception #0 (Magento\Framework\Exception\InputException): An ID is needed. Set the ID and try again.
#1 Magento\Sales\Model\OrderRepository\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#2 Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#3 Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php:23]
#4 Magento\Sales\Model\OrderRepository\Interceptor->get() called at [vendor/payu/magento24-payment-gateway/Model/RepaymentResolver.php:45]
#5 PayU\PaymentGateway\Model\RepaymentResolver->isRepayment() called at [vendor/payu/magento24-payment-gateway/Controller/Order/RepayView.php:45]
#6 PayU\PaymentGateway\Controller\Order\RepayView->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#7 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#8 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#9 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#10 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#11 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->___callPlugins() called at [generated/code/PayU/PaymentGateway/Controller/Order/RepayView/Interceptor.php:23]
#12 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#13 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#14 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#15 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->___callPlugins() called at [generated/code/PayU/PaymentGateway/Controller/Order/RepayView/Interceptor.php:32]
#17 PayU\PaymentGateway\Controller\Order\RepayView\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#18 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#19 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#22 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71]
#24 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#26 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#27 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#28 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#29 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

This happens on an order placed by a logged-in user as well as an not logged in. For a logged in one, it is possible to go from the profile page correctly - there is no error there.

The module was installed using composer. The problem is in a production environment as well as sandbox payu.

**Comment by regdos** [comment]
Hello, 

We confirm bug, we working on fix.
