### ISSUE TITLE
Store cards in Sandbox PayU

### ISSUE THREAD

**Issue by LukSky24** [PayU-EMEA/plugin_magento_24#18]
Hey!
I have a question about storing cards in PayU Sandbox. Is it possible?
We are using this module for our Magento project and I enabled storing cards data in payment option. 
I used data for testing cards (from PayU Sandbox) and I am still getting `Tokenization failed due to "400"` And I don't know what it means? Can you tell me where can I found some test cards to save it on sandbox or maybe tell me if it not possible to test this functionality on Sandbox?
![image](https://user-images.githubusercontent.com/52952445/156174384-bbffd55a-1eaa-42b9-b2c8-f5b4008a581b.png)

I will be pleased for any answer.

EDIT: I used another config for test site in PayU Sandbox and I saved (probably) card where I was buying something in store. But now when I want to get this cards for client I am getting this error:
`Oauth error: [code=400], [message=invalid_grant - Unauthorized grant type: trusted_merchant] [] []`

**Comment by regdos** [comment]
POS, którego Pan używa prawdopodobnie nie ma włączonej tokenizacji. Proszę o kontakt z BOK żeby sprawdzili, konfigurację.
