### ISSUE TITLE
Cannot install using composer

### ISSUE THREAD

**Issue by karamucho** [PayU-EMEA/plugin_magento_24#2]
I have got this error:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - payu/magento24-payment-gateway 1.0.1 requires magento/module-sales 103.0.* -> no matching package found.
    - payu/magento24-payment-gateway 1.0.0 requires magento/module-sales 103.0.* -> no matching package found.
    - Installation request for payu/magento24-payment-gateway ^1.0 -> satisfiable by payu/magento24-payment-gateway[1.0.0, 1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
`

**Comment by gkopec** [comment]
I just installed it via composer on Mac OS (PHP 7.4) without any issues.

**Comment by regdos** [comment]
@karamucho Are you sure you are trying to install plugin on M 2.4?
I confirm that on the  M 2.4 works correctly.
```
composer require payu/magento24-payment-gateway
Using version ^1.0 for payu/magento24-payment-gateway
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing payu/magento24-payment-gateway (1.0.1): Downloading (100%)
