### ISSUE TITLE
Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/payu/magento24-payment-gateway/Model/CreateOrderResolver.php on line 444

### ISSUE THREAD

**Issue by taursus96** [PayU-EMEA/plugin_magento_24#25]
Creating orders from cmd/cron won't work because of this error on php 8.2:
Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/payu/magento24-payment-gateway/Model/CreateOrderResolver.php on line 444

Fix: payu/magento24-payment-gateway/Model/CreateOrderResolver.php:444

Should be:
$ip = explode(',', trim($this->http->getClientIp() ?? ''));

Instead of:
$ip = explode(',', trim($this->http->getClientIp()));

**Comment by regdos** [comment]
From version 2.x, the method of obtaining the IP address has been changed.
