### ISSUE TITLE
ERROR_SYNTAX - Bad syntax on /api/v2_1/orders request

### ISSUE THREAD

**Issue by improf** [PayU-EMEA/plugin_magento_24#27]
### General

Test was done on sandbox mode.

Magento:
"magento/product-community-edition": "2.4.6-p3"

PayU Plugin:
"payu/magento24-payment-gateway": "2.0.0

### AS-IS
There is no possibility to place order that has more then 1 product, to be precise 1 configurable products plus another product.
The error that we are received:
`payULogger.CRITICAL: ERROR_SYNTAX - Bad syntax {"order":{"description":"Zamówienie L1110525994 [xxx]","customerIp":"xxx","extOrderId":"L1110525994_65b7a1bed66ba","notifyUrl":"https://abc/pl/payu/data/getNotify/type/payu_gateway/store/1/","continueUrl":"https://abc/pl/checkout/onepage/success/","totalAmount":"31980","currencyCode":"PLN","merchantPosId":"xxx","payMethods":{"payMethod":{"type":"PBL","value":"p"}},"buyer":{"email":"abc@email.com","firstName":"Test","lastName":"Test","phone":"435434543","language":"pl","delivery":{"street":"Szkolna 21","postalCode":"41-500","city":"Gdynia","countryCode":"PL"}},"products":{"0":{"quantity":1.0,"name":"Bluza Zielona","unitPrice":"14990"},"2":{"quantity":1.0,"name":"Bluza Beżowa","unitPrice":"16990"},"3":{"quantity":1,"name":"Shipment [Kurier DPD]","unitPrice":"0"}}}} []
`

### REASON
In class [[Gateway/Request/ProductsDataBuilder.php ](https://github.com/PayU-EMEA/plugin_magento_24/blob/v2.0.0/Gateway/Request/ProductsDataBuilder.php) ](https://github.com/PayU-EMEA/plugin_magento_24/blob/1966a3a2d0b534b5b9b043c6b87ce2e6df63cf73/Gateway/Request/ProductsDataBuilder.php#L35) there is a loop through order items. 
If there are few simple products, everything works fine.
If there are configurable product plus another product of any type the logic is still working fine but result array has wrong keys (they are't sequential). For example if we have 1 configurable product + 1 simple product the result array will be like this (configurable products is save on quote as 2 separated products - parent and child option, child option is omitted by PayU logic here):
`[
'0' => [...],
'2' => [...],
]`

It has impact on json encoding in https://github.com/PayU-EMEA/plugin_magento_24/blob/1966a3a2d0b534b5b9b043c6b87ce2e6df63cf73/lib/OpenPayU/Util.php#L125 - it will return products as object of objects, meanwhile PayU API requires array of objects.
https://developers.payu.com/europe/pl/api#tag/Order/operation/create-an-order

This is due to this line: https://github.com/PayU-EMEA/plugin_magento_24/blob/1966a3a2d0b534b5b9b043c6b87ce2e6df63cf73/Gateway/Request/ProductsDataBuilder.php#L61
It shuld be moved to the end of this if statement: https://github.com/PayU-EMEA/plugin_magento_24/blob/1966a3a2d0b534b5b9b043c6b87ce2e6df63cf73/Gateway/Request/ProductsDataBuilder.php#L37
Then json encode will return data in correct structure.

### TO-BE
Fix is provided directly to PayU Magento Plugin.

**Comment by regdos** [comment]
Thanks for analyze.
