### ISSUE TITLE
TypeError: PayU\PaymentGateway\Model\RepayOrder::execute(): Argument #3

### ISSUE THREAD

**Issue by LukaszZabielskiMonogo** [PayU-EMEA/plugin_magento_24#30]
`TypeError: PayU\PaymentGateway\Model\RepayOrder::execute(): Argument #3 ($payUMethodType) must be of type string, null given, called in /code/vendor/payu/magento24-payment-gateway/Gateway/Response/RepayOrderCreateResponseHandler.php on line 34 and defined in /code/vendor/payu/magento24-payment-gateway/Model/RepayOrder.php:39`

- PHP 8.2
- Magento 2.4.6-p4
- PayU 2.0.2

### I try to create repayment transaction for magento order by "PBL" method type, without write payu method code.

**For example**
`$returnData = $repayResolver->execute(
                    $order,
                    (string)$order->getPayment()->getMethod(),
                    '',
                    'PBL',
                    []
                );`

**I created patch, the patch working good.**

`diff --git a/Gateway/Response/RepayOrderCreateResponseHandler.php b/Gateway/Response/RepayOrderCreateResponseHandler.php
index c06b649..0132bf4 100644
minus a/Gateway/Response/RepayOrderCreateResponseHandler.php
minus b/Gateway/Response/RepayOrderCreateResponseHandler.php
@@ -31,7 +31,7 @@ class RepayOrderCreateResponseHandler implements HandlerInterface
         $payUMethodType = RepaySubjectReader::readPayuMethodType($handlingSubject);
         $browser = RepaySubjectReader::readPayuBrowser($handlingSubject);
`

`$this->payURepayOrder->execute($order, $method, $payUMethodType, $payUMethod, $browser, $response['orderId']);`
`$this->payURepayOrder->execute($order, $method, (string)$payUMethodType, (string)$payUMethod, $browser, $response['orderId']);`

The execute method parameters have to be typed by string **(string)$payUMethodType, (string)$payUMethod**

**Comment by regdos** [comment]
Hej,
Chcesz wywołać repaymnet programistycznie nie z frontów?  
Jak efekt chcesz uzyskać? Przekierowanie do formatki płatności PayU bez wybranej metody?

**Comment by LukaszZabielskiMonogo** [comment]
> Hej, Chcesz wywołać repaymnet programistycznie nie z frontów? Jak efekt chcesz uzyskać? Przekierowanie do formatki płatności PayU bez wybranej metody?

Przekierowanie do formatki płatności PayU bez wybranej metody (programistycznie). Przed code refactoring modułu było to możliwe. Mój moduł rozszerza moduł PayU. Sprawdzam, jeśli płatność w PayU jest nie opłacona po 5 min od złożenia zamówienia, wysyłam klientowi na email link z możliwością ponowienia płatności. Kiedy zdefiniuję w tej metodzie kod płatności, to działa i przenosi do konkretnej metody płatności w PayU, to jest OK. Ale w chcę aby klient był przekierowany na ogólną stronę płatności, aby miał możliwość wybrania innej lub tej samej metody płatności. Po wprowadzeniu łatki, metoda działa zgodnie z oczekiwaniem.

Ogólnie wasz moduł nie posiada błędu sam w sobie, ale przy próbie rozszerzenia metoda zwraca błąd logiczny. Bo istnieje  w PayU przekierowanie na ogólną stronę płatności bez podawania kodów.

CC: @regdos

**Comment by regdos** [comment]
Poprawione tylko w trochę innym miejscu. 

A dlaczego nie korzystasz z ponowienia, które jest w pluginie?

**Comment by LukaszZabielskiMonogo** [comment]
> Poprawione tylko w trochę innym miejscu.
> 
> A dlaczego nie korzystasz z ponowienia, które jest w pluginie?

Korzystam z ponowienia, które jest w pluginie. Dla mojego klienta jest to rozwiązanie mało intuicyjne i niewystarczające. W panelu użytkownika da się ponownie opłacić dane zamówienie, ale właśnie metodą płatności tą samą co podczas składania zamówienia. Wysyłka maila z linkiem do ponowienia płatności i umożliwienie zapłaty dowolną metodą (blik, apple pay itd...) jest wartością dodaną. W przypadku błędu, czy niemożliwości zapłaty daną kartą.
