### ISSUE TITLE
After update to v 1.0.3 cannot place order

### ISSUE THREAD

**Issue by karamucho** [PayU-EMEA/plugin_magento_24#5]
After placing the order, the screen freezes, an e-mail about payment is sent to the customer's, after refreshing the page, you can complete the order using another payment method 
![obraz](https://user-images.githubusercontent.com/11872461/118855579-2f3d7100-b8d6-11eb-9425-a7d833b7be82.png)
My magento ver. is 2.4.0, in this picture I veiled the address so that's not a problem.
I have one more question - is it possible to change the displayed payment methods? Currently (I tested in sandbox mode) regardless of the configuration in the "Payment Methods Order" field: (c, ma, vc, blik) or (c, ma, vc, blik, m, w, o, i, p, g, gbx, nlx, ib, l, ab, ps, wm, wc, bs, nstb, sgb, plsb, b) the same payment methods are displayed, if this is the case, it would be better to display the selection of payment methods on the payU website, not the store's website.

**Comment by regdos** [comment]
@karamucho Can we switch to Polish?

**Comment by karamucho** [comment]
OK Przejdźmy na polski, nie wiem czy problem leży po stronie modułu czy sklepu - po odinstalowaniu modułu na innym module płatności wszystko działa ok

**Comment by Bartlomiejsz** [comment]
@regdos mogę potwierdzić błąd, też występuje w moim wypadku i z tego co udało mi się sprawdzić powodem jest usunięcie tej linii - https://github.com/PayU-EMEA/plugin_magento_24/commit/99f41e6def4e48fefef55735d9c25be059aa28b8#diff-e505ab67d449b3f1de4caa376c8d3881ae4de792a0c454264aadea3f6af844fbL87
Problem występuje tylko jeśli jest włączone powiadomienie o ponownej płatności - w takiej sytuacji w trakcie przetwarzania https://github.com/PayU-EMEA/plugin_magento_24/commit/99f41e6def4e48fefef55735d9c25be059aa28b8#diff-e505ab67d449b3f1de4caa376c8d3881ae4de792a0c454264aadea3f6af844fbR61 jest rzucany wyjątek, bo wysyłka maila wymaga istniejącego już zamówienia, a przez usunięcie w.w. linii, nie jest ono jeszcze zapisane w momencie wysłania emaila

**Comment by flexcodenet** [comment]
> @regdos mogę potwierdzić błąd, też występuje w moim wypadku i z tego co udało mi się sprawdzić powodem jest usunięcie tej linii - [99f41e6#diff-e505ab67d449b3f1de4caa376c8d3881ae4de792a0c454264aadea3f6af844fbL87](https://github.com/PayU-EMEA/plugin_magento_24/commit/99f41e6def4e48fefef55735d9c25be059aa28b8#diff-e505ab67d449b3f1de4caa376c8d3881ae4de792a0c454264aadea3f6af844fbL87)
> Problem występuje tylko jeśli jest włączone powiadomienie o ponownej płatności - w takiej sytuacji w trakcie przetwarzania [99f41e6#diff-e505ab67d449b3f1de4caa376c8d3881ae4de792a0c454264aadea3f6af844fbR61](https://github.com/PayU-EMEA/plugin_magento_24/commit/99f41e6def4e48fefef55735d9c25be059aa28b8#diff-e505ab67d449b3f1de4caa376c8d3881ae4de792a0c454264aadea3f6af844fbR61) jest rzucany wyjątek, bo wysyłka maila wymaga istniejącego już zamówienia, a przez usunięcie w.w. linii, nie jest ono jeszcze zapisane w momencie wysłania emaila

Potwierdzam problem, też mam identyczną sytuację i gdy wyłączy się ponowienie płatności to problem znika. Kiedy jakiś fix?

**Comment by regdos** [comment]
@Bartlomiejsz @flexcodenet 
Próbujemy znaleźć właściwe rozwiązanie. 
Ta linia z zapisem została usunięta ponieważ i tak ten zapis jest potem robiony w normalnym procesie M2 ale przez dwa zapisy było generowane wielokrotnie zdarzenia związane ze zmianą statusu. 

Samo zamówienie cały czas istnieje w tym jednym żądaniu (w końcu na tym Observerze jest dostępne)  jedynie nie jest zapisane do bazy. NIe wiem dlaczego Magento_Weee wymaga tego zapisu.

**Comment by regdos** [comment]
@Bartlomiejsz @flexcodenet 
Proszę o przestestowanie poprawki https://github.com/PayU-EMEA/plugin_magento_24/commit/4876587519a33437d33eee773de1cb4124dbcdd9

i informację czy pomogło.

**Comment by flexcodenet** [comment]
> @Bartlomiejsz @flexcodenet
> Proszę o przestestowanie poprawki [4876587](https://github.com/PayU-EMEA/plugin_magento_24/commit/4876587519a33437d33eee773de1cb4124dbcdd9)
> 
> i informację czy pomogło.

@regdos u mnie podczas składania zamówienia pojawia się następujący problem

![image](https://user-images.githubusercontent.com/47887928/126974338-b6d70813-ae16-4e3b-a08f-3b1240371945.png)

**Comment by regdos** [comment]
@flexcodenet wymagane jest uruchomienie `bin/magento setup:di:compile` bo zmieniła sie sygnatura metody

**Comment by flexcodenet** [comment]
@regdos Działa poprawnie, nie znalazłem błędów. Lecz wciąż jest bezsensowne używanie opcji "ponowienie płatności" gdy jest nadawany status zamówienia "Anulowane" gdy jest negatywny komunikat o transakcji, ponieważ nie mogę zapłacić ponownie, a informacja jest, że "dziękujemy za złożenie zamówienia". Opisałem to tutaj: [https://github.com/PayU-EMEA/plugin_magento_24/issues/10](url)

**Comment by regdos** [comment]
Dziękuję za sprawdzenie.
