### ISSUE TITLE
Płatność kartą wyświetla się w panelu użytkownika gdy jest wyłączona

### ISSUE THREAD

**Issue by flexcodenet** [PayU-EMEA/plugin_magento_24#9]
W przypadku aktywacji ponowienia płatności, a jednocześnie PayU - karty są wyłączone, to w panelu użytkownika i tak się wyświetlają. Przez co wygląda to bardzo źle.

![image](https://user-images.githubusercontent.com/47887928/125626492-a514329d-8777-4497-a971-0ae84c42dabc.png)

**Comment by flexcodenet** [comment]
Czy ktoś sprawdza zgłaszane problemy na GitHub?

**Comment by regdos** [comment]
Owszem są sprawdzane. 
Rozumiem, że w normalnym procesie zakupowym nie pojawiają się karty tylko tak się dzieje podczas ponowienia płatności?

**Comment by flexcodenet** [comment]
Tak.

**Comment by flexcodenet** [comment]
Problem zgłosiłem też szerzej emailowo do działu IT, ale również cisza w tej kwestii.

**Comment by regdos** [comment]
@flexcodenet po wielu próbach nie udało mi się uzyskać tego błędu. Proszę podać adres sklepu.

**Comment by flexcodenet** [comment]
@regdos Czy mogę mniej publiczny sposób przekazać link do sklepu testowego? Jakiś email do Pana?

**Comment by regdos** [comment]
@flexcodenet proszę przesłać dane do BOK PayU powołując się na zgłoszenie i zostaną mi one przekazane.

**Comment by flexcodenet** [comment]
@regdos Gotowe

**Comment by flexcodenet** [comment]
@regdos w wersji 1.0.4 błąd nie występuje.

**Comment by regdos** [comment]
W takim razie zamykam.
